app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_mail import Mail
from flask_migrate import Migrate
import os

db = SQLAlchemy()
migrate = Migrate()
mail = Mail()
login_manager = LoginManager()

def create_app():
    app = Flask(__name__)

    # app configuration
    flask_env = os.getenv("FLASK_ENV", None)

    if flask_env == "development":
        app.config.from_object("config.DevelopConfig")
    elif flask_env == "testing":
        app.config.from_object("config.TestingConfig")
    else:
        app.config.from_object("config.ProductionConfig")
    
    # initialize plug-ins
    db.init_app(app)
    migrate.init_app(app, db)
    login_manager.init_app(app)
    mail.init_app(app)

    #import db models for initializing db
    from . import dbmodels

    # app context
    with app.app_context():
        # initialize database
        db.create_all()

        # blueprints
        from . import routes
        
        app.register_blueprint(routes.auth_bp)
        app.register_blueprint(routes.base_bp)

        return app

app/dbmodels/__init__.py
from .user import *

app/routes/__init__.py
from .auth import auth_bp
from .loginmanager import login_manager
from .base import base_bp

app/routes/auth.py
from flask import Blueprint
from flask_login import login_required
from app.services import auth

auth_bp = Blueprint(
    "auth_bp", __name__
)

@auth_bp.route('/login/', methods=['GET', 'POST'])
def login():
    return auth.login()

@auth_bp.route('/signup/', methods=['GET','POST'])
def signup():
    return auth.signup()

@auth_bp.route('/logout/')
@login_required
def logout():
    return auth.logout()

@auth_bp.route('/forgot_password/', methods=['GET', 'POST'])
def forgot():
    return auth.forgot()

@auth_bp.route('/reset_password/<token>', methods=['GET','POST'])
def newpass(token):
    return auth.newpass(token)

app/routes/base.py
from flask import Blueprint, render_template

base_bp = Blueprint(
    "base_bp", __name__
)

@base_bp.route('/', methods=['GET'])
def home():
    return render_template("base.html",page_title="Critiq")

app/routes/loginmanager.py
from app import login_manager
from app.dbmodels import User
from flask import flash, redirect, url_for

@login_manager.user_loader
def load_user(user_id):
    if user_id is not None:
        return User.query.get(user_id)
    return None

@login_manager.unauthorized_handler
def unauthorized():
    """Redirect unauthorized users to Login page."""
    flash('You must be logged in to view that page.')
    return redirect(url_for('base_bp.home'))

app/services/__init__.py
from . import auth

app/services/auth.py
from flask import (redirect, render_template, 
                    flash, url_for)
from flask_login import logout_user, current_user, login_user
from app import mail
from flask_mail import Message
import os, datetime
from dotenv import load_dotenv
from app.dbmodels import get_user_from_token, user_from_email, create_user
from app.forms.auth import *

load_dotenv()

def login():
    if current_user.is_authenticated:
        return redirect(url_for('base_bp.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = user_from_email(form.email.data)
        if user and user.check_password(password=form.password.data):
            login_user(user, remember=form.remember.data)
            return redirect(url_for('base_bp.home'))
        flash('Invalid username/password combination')
        return redirect(url_for('auth_bp.login'))
    return render_template('auth/login.html', form=form, page_title="Critiq Log In")

def signup():
    form = SignUpForm()
    if form.validate_on_submit():
        existing_user = user_from_email(form.email.data)
        if existing_user is None:
            user = create_user(form.username.data, form.email.data, form.password.data)
            login_user(user)
            flash("Success","info")
            return redirect(url_for('base_bp.home'))
        flash('A user already exists with that email address.')
    return render_template('auth/signup.html',form=form, page_title="Critiq Sign Up")

def logout():
    logout_user()
    flash('You have successfully logged out.', "info")
    return redirect(url_for('auth_bp.login'))

def forgot():
    form = ForgotPasswordForm()
    if form.validate_on_submit():
        user = user_from_email(form.email.data)
        if user:
            token = user.get_token(expires=24)
            url = url_for('newpass', token=token, _external=True)
            msg = Message()
            msg.subject = "Critiq Password Reset"
            msg.sender = os.environ.get('MAIL_USERNAME')
            msg.recipients = [user.email]
            msg.html = render_template('auth/reset_email.html',
                                url=url, date=datetime.date.today, 
                                username=user.username, time=24)
            mail.send(msg)
            flash("Password Reset. Please check your email for instructions.")
            return(redirect(url_for('base_bp.home')))
        else:
            flash("There are no users with this email. Sign up or try again.")
            return redirect(url_for('auth_bp.signup'))
    return render_template('auth/forgotpass.html',form=form, page_title="Forgot Password")

def newpass(token):
    try: 
        user = get_user_from_token(token)
    except:
        flash("Link expired.")
        return redirect(url_for('base_bp.home'))

    form = NewPassword()
    if form.validate_on_submit():
        user.set_password(form.password.data)
        return redirect(url_for('auth_bp.login'))
    return render_template('auth/newpass.html', form=form, page_title="New Password")

app/templates/base.html
<!doctype html>
<html lang='en'>

<head>
{% block header %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Svetha Pulavarty">
    
    {% block styles %}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <link rel="stylesheet" href="{{ url_for('static', filename='base_styles.css') }}">
    {% endblock styles %}

    <title>{{page_title}}</title>
{% endblock header %}
</head>

<body>

{% block nav %}
<div class='container-fluid'>
    <nav class='navbar navbar-expand-md navbar-light bg-light rounded'> 
        <div class="container-fluid">
            {% block homenav %} <a class="navbar-brand" href="{{url_for('base_bp.home')}}" aria-current="page">Critiq</a> {% endblock homenav %}
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mainNav" aria-controls="mainNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div id="mainNav" class="collapse navbar-collapse">
                <div class="navbar-nav me-auto">
                    {% if current_user.is_authenticated %}
                    {% block logoutnav %} <a class="nav-link" href="{{url_for('auth_bp.logout')}}">Logout</a> {% endblock logoutnav %}
                    {% else %}
                    {% block loginnav %} <a class="nav-link" href="{{url_for('auth_bp.login')}}">Log In</a> {% endblock loginnav %}
                    {% block signupnav %} <a class="nav-link" href="{{url_for('auth_bp.signup')}}">Sign Up</a> {% endblock signupnav %}
                    {% endif %}
                <div>
            </div>
        </div>
    </nav>
</div>
{% endblock nav %}

<div class="container">
{% for category, message in get_flashed_messages(with_categories=true) %}
    <!-- Categories: primary, secondary, success, danger, warning, info, light, dark -->
        <div class="alert alert-{{ category }} alert-dismissible" role="alert"> 
            {{message}}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
{% endfor %}
</div>

{% block content %}
<div class="container">
{% if current_user.is_authenticated %}
    <h1>Welcome! Thanks for Signing In</h1>
{% else %}
    <h1>Welcome! Please Sign Up</h1>
{% endif %}
</div>
{% endblock %}

<footer>

</footer>
{% block scripts %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
{% endblock scripts %}
</body>